version: '3.9'

services:
  web:
    build: .
    command:  python djangoapp/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - net1

networks:
  net1:
    external:
      name: unasus_network