version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - unasus_network

  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "13002:5432"
    networks:
      - unasus_network

  charge:
    build: .
    command: python charge/charge.py
    volumes:
      - .:/code
    depends_on:
      - web
    networks:
      - unasus_network

  app:
    build:
      dockerfile: frontend/frontv1/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - unasus_network

networks:
  unasus_network:
    driver: bridge

volumes:
  postgres_data:
