version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 23002:5432
    networks:
      - net1

networks:
  net1:
    name: unasus_network
    driver: bridge

volumes:
  postgres_data:
