# Generated by Django 5.0.6 on 2024-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=11, unique=True)),
                ('Nome', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefone', models.CharField(max_length=15)),
                ('Municipio', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('Situacao', models.CharField(max_length=20)),
                ('Ciclo', models.CharField(max_length=10)),
                ('Lista', models.CharField(max_length=50)),
                ('DSEI', models.BooleanField(default=False)),
                ('Matricula', models.IntegerField(unique=True)),
                ('TurmaTutor', models.CharField(max_length=50)),
                ('Data', models.DateField()),
                ('Condição', models.CharField(max_length=50)),
                ('DataSolicitacaoMudanca', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
