# Generated by Django 5.0.6 on 2024-06-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Date',
            field=models.CharField(max_length=50),
        ),
    ]
