# Generated by Django 5.1.1 on 2024-09-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('ibge_code', models.CharField(max_length=255)),
                ('city_profile', models.CharField(max_length=255)),
                ('vulnerability_profile', models.CharField(max_length=255)),
                ('ine', models.CharField(max_length=255)),
                ('cnes_code', models.CharField(max_length=255)),
                ('ubs_type', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('offering', models.CharField(max_length=255)),
                ('action_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='ubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='unasus_registros.ubs'),
        ),
    ]
