# Generated by Django 5.0.6 on 2024-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='disability',
            field=models.BooleanField(default=False),
        ),
    ]
