# Generated by Django 5.1.1 on 2024-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0002_ubs_student_ubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubs',
            name='name',
            field=models.CharField(default='UBS Padrão', max_length=255),
        ),
    ]
