# Generated by Django 5.0.6 on 2024-06-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0003_alter_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Condition',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Cycle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='List',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Municipality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='State',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='TutorClass',
            field=models.CharField(max_length=255),
        ),
    ]
