# Generated by Django 5.1.1 on 2024-09-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0003_ubs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubs',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
