# Generated by Django 5.1.1 on 2024-09-16 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0004_ubs_total_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='unasus_registros.ubs')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unasus_registros.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('patient_name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unasus_registros.doctor')),
                ('ubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unasus_registros.ubs')),
            ],
        ),
    ]
