# Generated by Django 5.0.6 on 2024-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0004_alter_student_condition_alter_student_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
    ]
