# Generated by Django 5.0.6 on 2024-06-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0005_alter_student_email_alter_student_enrollmentnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='EnrollmentNumber',
            field=models.CharField(max_length=255),
        ),
    ]
