# Generated by Django 5.0.6 on 2024-05-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Condição',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Ciclo',
            new_name='Cycle',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Data',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Matricula',
            new_name='EnrollmentNumber',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Lista',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Municipio',
            new_name='Municipality',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Nome',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Telefone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='DataSolicitacaoMudanca',
            new_name='RequestChangeDate',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='UF',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Situacao',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='TurmaTutor',
            new_name='TutorClass',
        ),
    ]
