# Generated by Django 5.0.6 on 2024-05-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unasus_registros', '0002_rename_condição_aluno_condition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Student',
        ),
    ]
